import { TokenTypes } from "../../../constants";

export default [
  {
    type: TokenTypes.OpenTagStart,
    content: "<div",
    startPosition: 0,
    endPosition: 3,
  },
  {
    type: TokenTypes.AttributeKey,
    content: "key",
    startPosition: 5,
    endPosition: 7,
  },
  {
    type: TokenTypes.AttributeAssignment,
    content: "=",
    startPosition: 10,
    endPosition: 10,
  },
  {
    type: TokenTypes.AttributeValue,
    content: "value",
    startPosition: 11,
    endPosition: 15,
  },
  {
    type: TokenTypes.AttributeKey,
    content: "and-another",
    startPosition: 18,
    endPosition: 28,
  },
  {
    type: TokenTypes.AttributeAssignment,
    content: "=",
    startPosition: 29,
    endPosition: 29,
  },
  {
    type: TokenTypes.AttributeValue,
    content: "value",
    startPosition: 32,
    endPosition: 36,
  },
  {
    type: TokenTypes.OpenTagEnd,
    content: ">",
    startPosition: 37,
    endPosition: 37,
  },
  {
    type: TokenTypes.CloseTag,
    content: "</div>",
    startPosition: 38,
    endPosition: 43,
  },
  {
    type: TokenTypes.Text,
    content: "\n\n",
    startPosition: 44,
    endPosition: 45,
  },

  {
    type: TokenTypes.OpenTagStart,
    content: "<span",
    startPosition: 46,
    endPosition: 50,
  },
  {
    type: TokenTypes.AttributeKey,
    content: "some",
    startPosition: 52,
    endPosition: 55,
  },
  {
    type: TokenTypes.AttributeAssignment,
    content: "=",
    startPosition: 56,
    endPosition: 56,
  },
  {
    type: TokenTypes.AttributeValue,
    content: "custom-attribute",
    startPosition: 57,
    endPosition: 72,
  },
  {
    type: TokenTypes.OpenTagEnd,
    content: ">",
    startPosition: 73,
    endPosition: 73,
  },
  {
    type: TokenTypes.Text,
    content: "\n  some text\n\n  ",
    startPosition: 74,
    endPosition: 89,
  },
  {
    type: TokenTypes.OpenTagStart,
    content: "<custom-element",
    startPosition: 90,
    endPosition: 104,
  },
  {
    type: TokenTypes.AttributeKey,
    content: "and",
    startPosition: 106,
    endPosition: 108,
  },
  {
    type: TokenTypes.AttributeAssignment,
    content: "=",
    startPosition: 109,
    endPosition: 109,
  },
  {
    type: TokenTypes.AttributeValue,
    content: "here",
    startPosition: 110,
    endPosition: 113,
  },
  {
    type: TokenTypes.AttributeKey,
    content: "and-even",
    startPosition: 119,
    endPosition: 126,
  },
  {
    type: TokenTypes.AttributeAssignment,
    content: "=",
    startPosition: 128,
    endPosition: 128,
  },
  {
    type: TokenTypes.AttributeValue,
    content: "here",
    startPosition: 130,
    endPosition: 133,
  },
  {
    type: TokenTypes.OpenTagEnd,
    content: ">",
    startPosition: 137,
    endPosition: 137,
  },
  {
    type: TokenTypes.Text,
    content: "\n    custom element\n    text\n  ",
    startPosition: 138,
    endPosition: 168,
  },
  {
    type: TokenTypes.CloseTag,
    content: "</custom-element>",
    startPosition: 169,
    endPosition: 185,
  },
  {
    type: TokenTypes.Text,
    content: "\n",
    startPosition: 186,
    endPosition: 186,
  },
  {
    type: TokenTypes.CloseTag,
    content: "</span>",
    startPosition: 187,
    endPosition: 193,
  },
  {
    type: TokenTypes.Text,
    content: "\n",
    startPosition: 194,
    endPosition: 194,
  },
];
