import { TokenTypes } from "../../../constants";

export default [
  {
    type: TokenTypes.OpenTagStart,
    content: "<div",
    startPosition: 0,
    endPosition: 3,
  },
  {
    type: TokenTypes.OpenTagEnd,
    content: ">",
    startPosition: 4,
    endPosition: 4,
  },
  {
    type: TokenTypes.Text,
    content: "\n  ",
    startPosition: 5,
    endPosition: 7,
  },
  {
    type: TokenTypes.OpenTagStart,
    content: "<span",
    startPosition: 8,
    endPosition: 12,
  },
  {
    type: TokenTypes.AttributeKey,
    content: "class",
    startPosition: 14,
    endPosition: 18,
  },
  {
    type: TokenTypes.AttributeAssignment,
    content: "=",
    startPosition: 19,
    endPosition: 19,
  },
  {
    type: TokenTypes.AttributeValueWrapperStart,
    content: "'",
    startPosition: 20,
    endPosition: 20,
  },
  {
    type: TokenTypes.AttributeValue,
    content: "test class",
    startPosition: 21,
    endPosition: 30,
  },
  {
    type: TokenTypes.AttributeValueWrapperEnd,
    content: "'",
    startPosition: 31,
    endPosition: 31,
  },
  {
    type: TokenTypes.AttributeKey,
    content: "data-test",
    startPosition: 33,
    endPosition: 41,
  },
  {
    type: TokenTypes.AttributeAssignment,
    content: "=",
    startPosition: 42,
    endPosition: 42,
  },
  {
    type: TokenTypes.AttributeValueWrapperStart,
    content: "'",
    startPosition: 43,
    endPosition: 43,
  },
  {
    type: TokenTypes.AttributeValue,
    content: "data<test>",
    startPosition: 44,
    endPosition: 53,
  },
  {
    type: TokenTypes.AttributeValueWrapperEnd,
    content: "'",
    startPosition: 54,
    endPosition: 54,
  },
  {
    type: TokenTypes.OpenTagEnd,
    content: ">",
    startPosition: 55,
    endPosition: 55,
  },
  {
    type: TokenTypes.Text,
    content: "\n    some text\n\n    ",
    startPosition: 56,
    endPosition: 75,
  },
  {
    type: TokenTypes.OpenTagStart,
    content: "<div",
    startPosition: 76,
    endPosition: 79,
  },
  {
    type: TokenTypes.OpenTagEnd,
    content: ">",
    startPosition: 80,
    endPosition: 80,
  },
  {
    type: TokenTypes.Text,
    content: "\n      another text\n\n      ",
    startPosition: 81,
    endPosition: 107,
  },
  {
    type: TokenTypes.OpenTagStart,
    content: "<custom-element",
    startPosition: 108,
    endPosition: 122,
  },
  {
    type: TokenTypes.AttributeKey,
    content: "custom-attr",
    startPosition: 132,
    endPosition: 142,
  },
  {
    type: TokenTypes.AttributeAssignment,
    content: "=",
    startPosition: 143,
    endPosition: 143,
  },
  {
    type: TokenTypes.AttributeValueWrapperStart,
    content: "'",
    startPosition: 144,
    endPosition: 144,
  },
  {
    type: TokenTypes.AttributeValue,
    content: "custom >test",
    startPosition: 145,
    endPosition: 156,
  },
  {
    type: TokenTypes.AttributeValueWrapperEnd,
    content: "'",
    startPosition: 157,
    endPosition: 157,
  },
  {
    type: TokenTypes.AttributeKey,
    content: "with-spaces",
    startPosition: 167,
    endPosition: 177,
  },
  {
    type: TokenTypes.AttributeAssignment,
    content: "=",
    startPosition: 181,
    endPosition: 181,
  },
  {
    type: TokenTypes.AttributeValueWrapperStart,
    content: "'",
    startPosition: 184,
    endPosition: 184,
  },
  {
    type: TokenTypes.AttributeValue,
    content: "spaces test",
    startPosition: 185,
    endPosition: 195,
  },
  {
    type: TokenTypes.AttributeValueWrapperEnd,
    content: "'",
    startPosition: 196,
    endPosition: 196,
  },
  {
    type: TokenTypes.OpenTagEnd,
    content: ">",
    startPosition: 204,
    endPosition: 204,
  },
  {
    type: TokenTypes.Text,
    content: "\n        custom element\n        text\n      ",
    startPosition: 205,
    endPosition: 247,
  },
  {
    type: TokenTypes.CloseTag,
    content: "</custom-element>",
    startPosition: 248,
    endPosition: 264,
  },
  {
    type: TokenTypes.Text,
    content: "\n    ",
    startPosition: 265,
    endPosition: 269,
  },
  {
    type: TokenTypes.CloseTag,
    content: "</div>",
    startPosition: 270,
    endPosition: 275,
  },
  {
    type: TokenTypes.Text,
    content: "\n  ",
    startPosition: 276,
    endPosition: 278,
  },
  {
    type: TokenTypes.CloseTag,
    content: "</span>",
    startPosition: 279,
    endPosition: 285,
  },
  {
    type: TokenTypes.Text,
    content: "\n",
    startPosition: 286,
    endPosition: 286,
  },
  {
    type: TokenTypes.CloseTag,
    content: "</div>",
    startPosition: 287,
    endPosition: 292,
  },
  {
    type: TokenTypes.Text,
    content: "\n",
    startPosition: 293,
    endPosition: 293,
  },
];
