import { TokenTypes } from "../../../constants";

export default [
  {
    type: TokenTypes.CommentStart,
    content: "<!--",
    startPosition: 0,
    endPosition: 3,
  },
  {
    type: TokenTypes.CommentContent,
    content: " some comment ",
    startPosition: 4,
    endPosition: 17,
  },
  {
    type: TokenTypes.CommentEnd,
    content: "-->",
    startPosition: 18,
    endPosition: 20,
  },
  {
    type: TokenTypes.Text,
    content: "\n\n",
    startPosition: 21,
    endPosition: 22,
  },
  {
    type: TokenTypes.OpenTagStart,
    content: "<div",
    startPosition: 23,
    endPosition: 26,
  },
  {
    type: TokenTypes.OpenTagEnd,
    content: ">",
    startPosition: 27,
    endPosition: 27,
  },
  {
    type: TokenTypes.Text,
    content: "\n  ",
    startPosition: 28,
    endPosition: 30,
  },
  {
    type: TokenTypes.OpenTagStart,
    content: "<span",
    startPosition: 31,
    endPosition: 35,
  },
  {
    type: TokenTypes.OpenTagEnd,
    content: ">",
    startPosition: 36,
    endPosition: 36,
  },
  {
    type: TokenTypes.Text,
    content: "\n    ",
    startPosition: 37,
    endPosition: 41,
  },
  {
    type: TokenTypes.CommentStart,
    content: "<!--",
    startPosition: 42,
    endPosition: 45,
  },
  {
    type: TokenTypes.CommentContent,
    content: "another-one",
    startPosition: 46,
    endPosition: 56,
  },
  {
    type: TokenTypes.CommentEnd,
    content: "-->",
    startPosition: 57,
    endPosition: 59,
  },
  {
    type: TokenTypes.Text,
    content: "\n  ",
    startPosition: 60,
    endPosition: 62,
  },
  {
    type: TokenTypes.CloseTag,
    content: "</span>",
    startPosition: 63,
    endPosition: 69,
  },
  {
    type: TokenTypes.Text,
    content: "\n\n  ",
    startPosition: 70,
    endPosition: 73,
  },
  {
    type: TokenTypes.CommentStart,
    content: "<!--",
    startPosition: 74,
    endPosition: 77,
  },
  {
    type: TokenTypes.CommentContent,
    content: "\n\n  multi\n\n  line\n  ",
    startPosition: 78,
    endPosition: 97,
  },
  {
    type: TokenTypes.CommentEnd,
    content: "-->",
    startPosition: 98,
    endPosition: 100,
  },
  {
    type: TokenTypes.Text,
    content: "\n",
    startPosition: 101,
    endPosition: 101,
  },
  {
    type: TokenTypes.CloseTag,
    content: "</div>",
    startPosition: 102,
    endPosition: 107,
  },
  {
    type: TokenTypes.Text,
    content: "\n\n",
    startPosition: 108,
    endPosition: 109,
  },
  {
    type: TokenTypes.CommentStart,
    content: "<!--",
    startPosition: 110,
    endPosition: 113,
  },
  {
    type: TokenTypes.CommentContent,
    content: " closing\n\ncomment ",
    startPosition: 114,
    endPosition: 131,
  },
  {
    type: TokenTypes.CommentEnd,
    content: "-->",
    startPosition: 132,
    endPosition: 134,
  },
  {
    type: TokenTypes.Text,
    content: "\n\n",
    startPosition: 135,
    endPosition: 136,
  },
  {
    type: TokenTypes.CommentStart,
    content: "<!--",
    startPosition: 137,
    endPosition: 140,
  },
  {
    type: TokenTypes.CommentContent,
    content: "         spaces here          ",
    startPosition: 141,
    endPosition: 170,
  },
  {
    type: TokenTypes.CommentEnd,
    content: "-->",
    startPosition: 171,
    endPosition: 173,
  },
  {
    type: TokenTypes.Text,
    content: "\n",
    startPosition: 174,
    endPosition: 174,
  },
];
