import { TokenTypes } from "../../../constants";

export default [
  {
    type: TokenTypes.DoctypeStart,
    content: "<!DOCTYPE",
    startPosition: 0,
    endPosition: 8,
  },
  {
    type: TokenTypes.DoctypeEnd,
    content: ">",
    startPosition: 9,
    endPosition: 9,
  },
  {
    type: TokenTypes.Text,
    content: "\n\n",
    startPosition: 10,
    endPosition: 11,
  },
  {
    type: TokenTypes.DoctypeStart,
    content: "<!doctype",
    startPosition: 12,
    endPosition: 20,
  },
  {
    type: TokenTypes.DoctypeEnd,
    content: ">",
    startPosition: 21,
    endPosition: 21,
  },
  {
    type: TokenTypes.Text,
    content: "\n\n",
    startPosition: 22,
    endPosition: 23,
  },
  {
    type: TokenTypes.DoctypeStart,
    content: "<!DOCTYPE",
    startPosition: 24,
    endPosition: 32,
  },
  {
    type: TokenTypes.DoctypeAttributeWrapperStart,
    content: '"',
    startPosition: 34,
    endPosition: 34,
  },
  {
    type: TokenTypes.DoctypeAttribute,
    content: "some attribute",
    startPosition: 35,
    endPosition: 48,
  },
  {
    type: TokenTypes.DoctypeAttributeWrapperEnd,
    content: '"',
    startPosition: 49,
    endPosition: 49,
  },
  {
    type: TokenTypes.DoctypeAttributeWrapperStart,
    content: "'",
    startPosition: 51,
    endPosition: 51,
  },
  {
    type: TokenTypes.DoctypeAttribute,
    content: "another-one",
    startPosition: 52,
    endPosition: 62,
  },
  {
    type: TokenTypes.DoctypeAttributeWrapperEnd,
    content: "'",
    startPosition: 63,
    endPosition: 63,
  },
  {
    type: TokenTypes.DoctypeEnd,
    content: ">",
    startPosition: 65,
    endPosition: 65,
  },
  {
    type: TokenTypes.Text,
    content: "\n\n",
    startPosition: 66,
    endPosition: 67,
  },
  {
    type: TokenTypes.DoctypeStart,
    content: "<!DOCTYPE",
    startPosition: 68,
    endPosition: 76,
  },
  {
    type: TokenTypes.DoctypeAttribute,
    content: "html",
    startPosition: 78,
    endPosition: 81,
  },
  {
    type: TokenTypes.DoctypeAttribute,
    content: "PUBLIC",
    startPosition: 83,
    endPosition: 88,
  },
  {
    type: TokenTypes.DoctypeEnd,
    content: ">",
    startPosition: 89,
    endPosition: 89,
  },
  {
    type: TokenTypes.Text,
    content: "\n\n",
    startPosition: 90,
    endPosition: 91,
  },
  {
    type: TokenTypes.DoctypeStart,
    content: "<!DOCTYPE",
    startPosition: 92,
    endPosition: 100,
  },
  {
    type: TokenTypes.DoctypeAttribute,
    content: "HTML",
    startPosition: 102,
    endPosition: 105,
  },
  {
    type: TokenTypes.DoctypeAttribute,
    content: "PUBLIC",
    startPosition: 107,
    endPosition: 112,
  },
  {
    type: TokenTypes.DoctypeAttributeWrapperStart,
    content: '"',
    startPosition: 114,
    endPosition: 114,
  },
  {
    type: TokenTypes.DoctypeAttribute,
    content: "-//W3C//DTD HTML 4.01 Frameset//EN",
    startPosition: 115,
    endPosition: 148,
  },
  {
    type: TokenTypes.DoctypeAttributeWrapperEnd,
    content: '"',
    startPosition: 149,
    endPosition: 149,
  },
  {
    type: TokenTypes.DoctypeAttributeWrapperStart,
    content: '"',
    startPosition: 151,
    endPosition: 151,
  },
  {
    type: TokenTypes.DoctypeAttribute,
    content: "http://www.w3.org/TR/html4/frameset.dtd",
    startPosition: 152,
    endPosition: 190,
  },
  {
    type: TokenTypes.DoctypeAttributeWrapperEnd,
    content: '"',
    startPosition: 191,
    endPosition: 191,
  },
  {
    type: TokenTypes.DoctypeEnd,
    content: ">",
    startPosition: 192,
    endPosition: 192,
  },
  {
    type: TokenTypes.Text,
    content: "\n\n",
    startPosition: 193,
    endPosition: 194,
  },
  {
    type: TokenTypes.DoctypeStart,
    content: "<!DOCTYPE",
    startPosition: 195,
    endPosition: 203,
  },
  {
    type: TokenTypes.DoctypeAttribute,
    content: "HTML",
    startPosition: 207,
    endPosition: 210,
  },
  {
    type: TokenTypes.DoctypeAttribute,
    content: "PUBLIC",
    startPosition: 212,
    endPosition: 217,
  },
  {
    type: TokenTypes.DoctypeAttributeWrapperStart,
    content: "'",
    startPosition: 221,
    endPosition: 221,
  },
  {
    type: TokenTypes.DoctypeAttribute,
    content: "-//W3C//DTD HTML 4.01 Frameset//EN",
    startPosition: 222,
    endPosition: 255,
  },
  {
    type: TokenTypes.DoctypeAttributeWrapperEnd,
    content: "'",
    startPosition: 256,
    endPosition: 256,
  },
  {
    type: TokenTypes.DoctypeAttributeWrapperStart,
    content: '"',
    startPosition: 260,
    endPosition: 260,
  },
  {
    type: TokenTypes.DoctypeAttribute,
    content: "http://www.w3.org/TR/html4/frameset.dtd",
    startPosition: 261,
    endPosition: 299,
  },
  {
    type: TokenTypes.DoctypeAttributeWrapperEnd,
    content: '"',
    startPosition: 300,
    endPosition: 300,
  },
  {
    type: TokenTypes.DoctypeEnd,
    content: ">",
    startPosition: 302,
    endPosition: 302,
  },
  {
    type: TokenTypes.Text,
    content: "\n",
    startPosition: 303,
    endPosition: 303,
  },
];
