import { TokenTypes } from "../../../constants";

export default [
  {
    type: TokenTypes.OpenTagStart,
    content: "<style",
    startPosition: 0,
    endPosition: 5,
  },
  {
    type: TokenTypes.AttributeKey,
    content: "type",
    startPosition: 7,
    endPosition: 10,
  },
  {
    type: TokenTypes.AttributeAssignment,
    content: "=",
    startPosition: 11,
    endPosition: 11,
  },
  {
    type: TokenTypes.AttributeValueWrapperStart,
    content: '"',
    startPosition: 12,
    endPosition: 12,
  },
  {
    type: TokenTypes.AttributeValue,
    content: "text/css",
    startPosition: 13,
    endPosition: 20,
  },
  {
    type: TokenTypes.AttributeValueWrapperEnd,
    content: '"',
    startPosition: 21,
    endPosition: 21,
  },
  {
    type: TokenTypes.AttributeKey,
    content: "custom",
    startPosition: 23,
    endPosition: 28,
  },
  {
    type: TokenTypes.AttributeAssignment,
    content: "=",
    startPosition: 29,
    endPosition: 29,
  },
  {
    type: TokenTypes.AttributeValueWrapperStart,
    content: '"',
    startPosition: 30,
    endPosition: 30,
  },
  {
    type: TokenTypes.AttributeValue,
    content: "attribute",
    startPosition: 31,
    endPosition: 39,
  },
  {
    type: TokenTypes.AttributeValueWrapperEnd,
    content: '"',
    startPosition: 40,
    endPosition: 40,
  },
  {
    type: TokenTypes.OpenTagEnd,
    content: ">",
    startPosition: 41,
    endPosition: 41,
  },
  {
    type: TokenTypes.Text,
    content: "\n  body {\n    background-color: white;\n  }\n",
    startPosition: 42,
    endPosition: 84,
  },
  {
    type: TokenTypes.CloseTag,
    content: "</style>",
    startPosition: 85,
    endPosition: 92,
  },
  {
    type: TokenTypes.Text,
    content: "\n\n",
    startPosition: 93,
    endPosition: 94,
  },
  {
    type: TokenTypes.OpenTagStart,
    content: "<div",
    startPosition: 95,
    endPosition: 98,
  },
  {
    type: TokenTypes.OpenTagEnd,
    content: ">",
    startPosition: 99,
    endPosition: 99,
  },
  {
    type: TokenTypes.Text,
    content: "\n  ",
    startPosition: 100,
    endPosition: 102,
  },
  {
    type: TokenTypes.OpenTagStart,
    content: "<style",
    startPosition: 103,
    endPosition: 108,
  },
  {
    type: TokenTypes.AttributeKey,
    content: "custom",
    startPosition: 114,
    endPosition: 119,
  },
  {
    type: TokenTypes.AttributeKey,
    content: "type",
    startPosition: 125,
    endPosition: 128,
  },
  {
    type: TokenTypes.AttributeAssignment,
    content: "=",
    startPosition: 129,
    endPosition: 129,
  },
  {
    type: TokenTypes.AttributeValueWrapperStart,
    content: '"',
    startPosition: 130,
    endPosition: 130,
  },
  {
    type: TokenTypes.AttributeValue,
    content: "text/css",
    startPosition: 131,
    endPosition: 138,
  },
  {
    type: TokenTypes.AttributeValueWrapperEnd,
    content: '"',
    startPosition: 139,
    endPosition: 139,
  },
  {
    type: TokenTypes.AttributeKey,
    content: "another-custom",
    startPosition: 146,
    endPosition: 159,
  },
  {
    type: TokenTypes.OpenTagEnd,
    content: ">",
    startPosition: 163,
    endPosition: 163,
  },
  {
    type: TokenTypes.Text,
    content: "\n    body {\n      background-color: red;\n    }\n  ",
    startPosition: 164,
    endPosition: 212,
  },
  {
    type: TokenTypes.CloseTag,
    content: "</style>",
    startPosition: 213,
    endPosition: 220,
  },
  {
    type: TokenTypes.Text,
    content: "\n",
    startPosition: 221,
    endPosition: 221,
  },
  {
    type: TokenTypes.CloseTag,
    content: "</div>",
    startPosition: 222,
    endPosition: 227,
  },
  {
    type: TokenTypes.Text,
    content: "\n",
    startPosition: 228,
    endPosition: 228,
  },
];
