import { TokenTypes } from "../../../constants";

export default [
  {
    type: TokenTypes.OpenTagStart,
    content: "<div",
    startPosition: 0,
    endPosition: 3,
  },
  {
    type: TokenTypes.OpenTagEnd,
    content: ">",
    startPosition: 4,
    endPosition: 4,
  },
  {
    type: TokenTypes.Text,
    content: "\n",
    startPosition: 5,
    endPosition: 5,
  },
  {
    type: TokenTypes.CloseTag,
    content: "</DIV>",
    startPosition: 6,
    endPosition: 11,
  },
  {
    type: TokenTypes.Text,
    content: "\n\n",
    startPosition: 12,
    endPosition: 13,
  },
  {
    type: TokenTypes.OpenTagStart,
    content: "<DIV",
    startPosition: 14,
    endPosition: 17,
  },
  {
    type: TokenTypes.OpenTagEnd,
    content: ">",
    startPosition: 18,
    endPosition: 18,
  },
  {
    type: TokenTypes.CloseTag,
    content: "</div>",
    startPosition: 19,
    endPosition: 24,
  },
  {
    type: TokenTypes.Text,
    content: "\n\n",
    startPosition: 25,
    endPosition: 26,
  },
  {
    type: TokenTypes.OpenTagStart,
    content: "<span",
    startPosition: 27,
    endPosition: 31,
  },
  {
    type: TokenTypes.OpenTagEnd,
    content: ">",
    startPosition: 32,
    endPosition: 32,
  },
  {
    type: TokenTypes.Text,
    content: "\n",
    startPosition: 33,
    endPosition: 33,
  },
  {
    type: TokenTypes.CloseTag,
    content: "</span>",
    startPosition: 34,
    endPosition: 40,
  },
  {
    type: TokenTypes.Text,
    content: "\n\n",
    startPosition: 41,
    endPosition: 42,
  },

  {
    type: TokenTypes.OpenTagStart,
    content: "<SPAN",
    startPosition: 43,
    endPosition: 47,
  },
  {
    type: TokenTypes.OpenTagEnd,
    content: ">",
    startPosition: 48,
    endPosition: 48,
  },
  {
    type: TokenTypes.CloseTag,
    content: "</SPAN>",
    startPosition: 49,
    endPosition: 55,
  },
  {
    type: TokenTypes.Text,
    content: "\n\n",
    startPosition: 56,
    endPosition: 57,
  },
  {
    type: TokenTypes.OpenTagStart,
    content: "<script",
    startPosition: 58,
    endPosition: 64,
  },
  {
    type: TokenTypes.OpenTagEnd,
    content: ">",
    startPosition: 65,
    endPosition: 65,
  },
  {
    type: TokenTypes.CloseTag,
    content: "</script>",
    startPosition: 66,
    endPosition: 74,
  },
  {
    type: TokenTypes.Text,
    content: "\n",
    startPosition: 75,
    endPosition: 75,
  },
  {
    type: TokenTypes.OpenTagStart,
    content: "<SCRIPT",
    startPosition: 76,
    endPosition: 82,
  },
  {
    type: TokenTypes.OpenTagEnd,
    content: ">",
    startPosition: 83,
    endPosition: 83,
  },
  {
    type: TokenTypes.Text,
    content: "\n",
    startPosition: 84,
    endPosition: 84,
  },
  {
    type: TokenTypes.CloseTag,
    content: "</SCRIPT>",
    startPosition: 85,
    endPosition: 93,
  },
  {
    type: TokenTypes.Text,
    content: "\n",
    startPosition: 94,
    endPosition: 94,
  },
  {
    type: TokenTypes.OpenTagStart,
    content: "<SCRIPT",
    startPosition: 95,
    endPosition: 101,
  },
  {
    type: TokenTypes.OpenTagEnd,
    content: ">",
    startPosition: 102,
    endPosition: 102,
  },
  {
    type: TokenTypes.CloseTag,
    content: "</script>",
    startPosition: 103,
    endPosition: 111,
  },
  {
    type: TokenTypes.Text,
    content: "\n",
    startPosition: 112,
    endPosition: 112,
  },
  {
    type: TokenTypes.OpenTagStart,
    content: "<script",
    startPosition: 113,
    endPosition: 119,
  },
  {
    type: TokenTypes.OpenTagEnd,
    content: ">",
    startPosition: 120,
    endPosition: 120,
  },
  {
    type: TokenTypes.Text,
    content: "\n",
    startPosition: 121,
    endPosition: 121,
  },
  {
    type: TokenTypes.CloseTag,
    content: "</SCRIPT>",
    startPosition: 122,
    endPosition: 130,
  },
  {
    type: TokenTypes.Text,
    content: "\n\n",
    startPosition: 131,
    endPosition: 132,
  },
  {
    type: TokenTypes.OpenTagStart,
    content: "<style",
    startPosition: 133,
    endPosition: 138,
  },
  {
    type: TokenTypes.OpenTagEnd,
    content: ">",
    startPosition: 139,
    endPosition: 139,
  },
  {
    type: TokenTypes.CloseTag,
    content: "</style>",
    startPosition: 140,
    endPosition: 147,
  },
  {
    type: TokenTypes.Text,
    content: "\n",
    startPosition: 148,
    endPosition: 148,
  },
  {
    type: TokenTypes.OpenTagStart,
    content: "<STYLE",
    startPosition: 149,
    endPosition: 154,
  },
  {
    type: TokenTypes.OpenTagEnd,
    content: ">",
    startPosition: 155,
    endPosition: 155,
  },
  {
    type: TokenTypes.Text,
    content: "\n",
    startPosition: 156,
    endPosition: 156,
  },
  {
    type: TokenTypes.CloseTag,
    content: "</STYLE>",
    startPosition: 157,
    endPosition: 164,
  },
  {
    type: TokenTypes.Text,
    content: "\n",
    startPosition: 165,
    endPosition: 165,
  },
  {
    type: TokenTypes.OpenTagStart,
    content: "<STYLE",
    startPosition: 166,
    endPosition: 171,
  },
  {
    type: TokenTypes.OpenTagEnd,
    content: ">",
    startPosition: 172,
    endPosition: 172,
  },
  {
    type: TokenTypes.CloseTag,
    content: "</style>",
    startPosition: 173,
    endPosition: 180,
  },
  {
    type: TokenTypes.Text,
    content: "\n",
    startPosition: 181,
    endPosition: 181,
  },
  {
    type: TokenTypes.OpenTagStart,
    content: "<style",
    startPosition: 182,
    endPosition: 187,
  },
  {
    type: TokenTypes.OpenTagEnd,
    content: ">",
    startPosition: 188,
    endPosition: 188,
  },
  {
    type: TokenTypes.CloseTag,
    content: "</STYLE>",
    startPosition: 189,
    endPosition: 196,
  },
  {
    type: TokenTypes.Text,
    content: "\n",
    startPosition: 197,
    endPosition: 197,
  },
];
