export enum TokenizerContextTypes {
  Data = "Data",
  OpenTagStart = "OpenTagStart",
  CloseTag = "CloseTag",
  Attributes = "Attributes",
  OpenTagEnd = "OpenTagEnd",
  AttributeKey = "AttributeKey",
  AttributeValue = "AttributeValue",
  AttributeValueBare = "AttributeValueBare",
  AttributeValueWrapped = "AttributeValueWrapped",
  ScriptContent = "ScriptContent",
  StyleContent = "StyleContent",
  DoctypeStart = "DoctypeStart",
  DoctypeEnd = "DoctypeEnd",
  DoctypeAttributes = "DoctypeAttributes",
  DoctypeAttributeWrapped = "DoctypeAttributeWrapped",
  DoctypeAttributeBare = "DoctypeAttributeBare",
  CommentStart = "CommentStart",
  CommentContent = "CommentContent",
  CommentEnd = "CommentEnd",
}
