export enum TokenTypes {
  Text = "Text",
  OpenTagStart = "OpenTagStart",
  AttributeKey = "AttributeKey",
  AttributeAssignment = "AttributeAssignment",
  AttributeValueWrapperStart = "AttributeValueWrapperStart",
  AttributeValue = "AttributeValue",
  AttributeValueWrapperEnd = "AttributeValueWrapperEnd",
  OpenTagEnd = "OpenTagEnd",
  CloseTag = "CloseTag",
  DoctypeStart = "DoctypeStart",
  DoctypeAttribute = "DoctypeAttribute",
  DoctypeAttributeWrapperStart = "DoctypeAttributeWrapperStart",
  DoctypeAttributeWrapperEnd = "DoctypeAttributeWrapperEnd",
  DoctypeEnd = "DoctypeEnd",
  CommentStart = "CommentStart",
  CommentContent = "CommentContent",
  CommentEnd = "CommentEnd",
}
