import { TokenTypes } from "../../../constants";
import { Token } from "../../../types";

export default [
  {
    type: TokenTypes.Text,
    content: "\n",
    startPosition: 0,
    endPosition: 0,
  },
  {
    type: TokenTypes.OpenTagStart,
    content: "<div",
    startPosition: 1,
    endPosition: 4,
  },
  {
    type: TokenTypes.AttributeKey,
    content: "class",
    startPosition: 6,
    endPosition: 10,
  },
  {
    type: TokenTypes.AttributeAssignment,
    content: "=",
    startPosition: 11,
    endPosition: 11,
  },
  {
    type: TokenTypes.AttributeValueWrapperStart,
    content: '"',
    startPosition: 12,
    endPosition: 12,
  },
  {
    type: TokenTypes.AttributeValue,
    content: "test",
    startPosition: 13,
    endPosition: 16,
  },
  {
    type: TokenTypes.AttributeValueWrapperEnd,
    content: '"',
    startPosition: 17,
    endPosition: 17,
  },
  {
    type: TokenTypes.OpenTagEnd,
    content: ">",
    startPosition: 18,
    endPosition: 18,
  },
  {
    type: TokenTypes.Text,
    content: "\n  ",
    startPosition: 19,
    endPosition: 21,
  },
  {
    type: TokenTypes.OpenTagStart,
    content: "<custom-elem",
    startPosition: 22,
    endPosition: 33,
  },
  {
    type: TokenTypes.AttributeKey,
    content: "required",
    startPosition: 35,
    endPosition: 42,
  },
  {
    type: TokenTypes.AttributeAssignment,
    content: "=",
    startPosition: 43,
    endPosition: 43,
  },
  {
    type: TokenTypes.AttributeValueWrapperStart,
    content: '"',
    startPosition: 44,
    endPosition: 44,
  },
  {
    type: TokenTypes.AttributeValue,
    content: "requered",
    startPosition: 45,
    endPosition: 52,
  },
  {
    type: TokenTypes.AttributeValueWrapperEnd,
    content: '"',
    startPosition: 53,
    endPosition: 53,
  },
  {
    type: TokenTypes.AttributeKey,
    content: "data-some",
    startPosition: 55,
    endPosition: 63,
  },
  {
    type: TokenTypes.AttributeAssignment,
    content: "=",
    startPosition: 64,
    endPosition: 64,
  },
  {
    type: TokenTypes.AttributeValueWrapperStart,
    content: '"',
    startPosition: 65,
    endPosition: 65,
  },
  {
    type: TokenTypes.AttributeValue,
    content: "thing",
    startPosition: 66,
    endPosition: 70,
  },
  {
    type: TokenTypes.AttributeValueWrapperEnd,
    content: '"',
    startPosition: 71,
    endPosition: 71,
  },
  {
    type: TokenTypes.OpenTagEnd,
    content: ">",
    startPosition: 72,
    endPosition: 72,
  },
  {
    type: TokenTypes.CloseTag,
    content: "</custom-elem>",
    startPosition: 73,
    endPosition: 86,
  },
  {
    type: TokenTypes.Text,
    content: "\n  \n  ",
    startPosition: 87,
    endPosition: 92,
  },
  {
    type: TokenTypes.OpenTagStart,
    content: "<button",
    startPosition: 93,
    endPosition: 99,
  },
  {
    type: TokenTypes.AttributeKey,
    content: "disabled",
    startPosition: 101,
    endPosition: 108,
  },
  {
    type: TokenTypes.AttributeKey,
    content: "class",
    startPosition: 110,
    endPosition: 114,
  },
  {
    type: TokenTypes.AttributeAssignment,
    content: "=",
    startPosition: 115,
    endPosition: 115,
  },
  {
    type: TokenTypes.AttributeValueWrapperStart,
    content: '"',
    startPosition: 116,
    endPosition: 116,
  },
  {
    type: TokenTypes.AttributeValue,
    content: "button",
    startPosition: 117,
    endPosition: 122,
  },
  {
    type: TokenTypes.AttributeValueWrapperEnd,
    content: '"',
    startPosition: 123,
    endPosition: 123,
  },
  {
    type: TokenTypes.AttributeKey,
    content: "required",
    startPosition: 125,
    endPosition: 132,
  },
  {
    type: TokenTypes.OpenTagEnd,
    content: ">",
    startPosition: 133,
    endPosition: 133,
  },
  {
    type: TokenTypes.CloseTag,
    content: "</button>",
    startPosition: 134,
    endPosition: 142,
  },
  {
    type: TokenTypes.Text,
    content: "\n  ",
    startPosition: 143,
    endPosition: 145,
  },
  {
    type: TokenTypes.OpenTagStart,
    content: "<button",
    startPosition: 146,
    endPosition: 152,
  },
  {
    type: TokenTypes.AttributeKey,
    content: "disabled",
    startPosition: 154,
    endPosition: 161,
  },
  {
    type: TokenTypes.AttributeKey,
    content: "required",
    startPosition: 163,
    endPosition: 170,
  },
  {
    type: TokenTypes.OpenTagEnd,
    content: ">",
    startPosition: 171,
    endPosition: 171,
  },
  {
    type: TokenTypes.CloseTag,
    content: "</button>",
    startPosition: 172,
    endPosition: 180,
  },
  {
    type: TokenTypes.Text,
    content: "\n  ",
    startPosition: 181,
    endPosition: 183,
  },
  {
    type: TokenTypes.OpenTagStart,
    content: "<button",
    startPosition: 184,
    endPosition: 190,
  },
  {
    type: TokenTypes.AttributeKey,
    content: "disabled",
    startPosition: 197,
    endPosition: 204,
  },
  {
    type: TokenTypes.AttributeKey,
    content: "class",
    startPosition: 211,
    endPosition: 215,
  },
  {
    type: TokenTypes.AttributeAssignment,
    content: "=",
    startPosition: 216,
    endPosition: 216,
  },
  {
    type: TokenTypes.AttributeValueWrapperStart,
    content: '"',
    startPosition: 217,
    endPosition: 217,
  },
  {
    type: TokenTypes.AttributeValue,
    content: "button disabled",
    startPosition: 218,
    endPosition: 232,
  },
  {
    type: TokenTypes.AttributeValueWrapperEnd,
    content: '"',
    startPosition: 233,
    endPosition: 233,
  },
  {
    type: TokenTypes.AttributeKey,
    content: "test",
    startPosition: 240,
    endPosition: 243,
  },
  {
    type: TokenTypes.AttributeAssignment,
    content: "=",
    startPosition: 244,
    endPosition: 244,
  },
  {
    type: TokenTypes.AttributeValueWrapperStart,
    content: '"',
    startPosition: 245,
    endPosition: 245,
  },
  {
    type: TokenTypes.AttributeValue,
    content: "attribute",
    startPosition: 246,
    endPosition: 254,
  },
  {
    type: TokenTypes.AttributeValueWrapperEnd,
    content: '"',
    startPosition: 255,
    endPosition: 255,
  },
  {
    type: TokenTypes.AttributeKey,
    content: "another",
    startPosition: 261,
    endPosition: 267,
  },
  {
    type: TokenTypes.AttributeAssignment,
    content: "=",
    startPosition: 268,
    endPosition: 268,
  },
  {
    type: TokenTypes.AttributeValueWrapperStart,
    content: '"',
    startPosition: 269,
    endPosition: 269,
  },
  {
    type: TokenTypes.AttributeValue,
    content: "attribute",
    startPosition: 270,
    endPosition: 278,
  },
  {
    type: TokenTypes.AttributeValueWrapperEnd,
    content: '"',
    startPosition: 279,
    endPosition: 279,
  },
  {
    type: TokenTypes.AttributeKey,
    content: "custom-one",
    startPosition: 285,
    endPosition: 294,
  },
  {
    type: TokenTypes.OpenTagEnd,
    content: ">",
    startPosition: 298,
    endPosition: 298,
  },
  {
    type: TokenTypes.CloseTag,
    content: "</button>",
    startPosition: 299,
    endPosition: 307,
  },
  {
    type: TokenTypes.Text,
    content: "\n  \n  ",
    startPosition: 308,
    endPosition: 313,
  },
  {
    type: TokenTypes.OpenTagStart,
    content: "<div",
    startPosition: 314,
    endPosition: 317,
  },
  {
    type: TokenTypes.AttributeAssignment,
    content: "=",
    startPosition: 319,
    endPosition: 319,
  },
  {
    type: TokenTypes.AttributeValueWrapperStart,
    content: "'",
    startPosition: 320,
    endPosition: 320,
  },
  {
    type: TokenTypes.AttributeValue,
    content: "only value",
    startPosition: 321,
    endPosition: 330,
  },
  {
    type: TokenTypes.AttributeValueWrapperEnd,
    content: "'",
    startPosition: 331,
    endPosition: 331,
  },
  {
    type: TokenTypes.AttributeKey,
    content: "'only-key'",
    startPosition: 333,
    endPosition: 342,
  },
  {
    type: TokenTypes.AttributeKey,
    content: "another",
    startPosition: 344,
    endPosition: 350,
  },
  {
    type: TokenTypes.AttributeAssignment,
    content: "=",
    startPosition: 351,
    endPosition: 351,
  },
  {
    type: TokenTypes.AttributeValueWrapperStart,
    content: '"',
    startPosition: 352,
    endPosition: 352,
  },
  {
    type: TokenTypes.AttributeValue,
    content: "attr",
    startPosition: 353,
    endPosition: 356,
  },
  {
    type: TokenTypes.AttributeValueWrapperEnd,
    content: '"',
    startPosition: 357,
    endPosition: 357,
  },
  {
    type: TokenTypes.AttributeAssignment,
    content: "=",
    startPosition: 359,
    endPosition: 359,
  },
  {
    type: TokenTypes.AttributeValueWrapperStart,
    content: '"',
    startPosition: 360,
    endPosition: 360,
  },
  {
    type: TokenTypes.AttributeValue,
    content: "only-value-2",
    startPosition: 361,
    endPosition: 372,
  },
  {
    type: TokenTypes.AttributeValueWrapperEnd,
    content: '"',
    startPosition: 373,
    endPosition: 373,
  },
  {
    type: TokenTypes.AttributeKey,
    content: '"only-key-2"',
    startPosition: 375,
    endPosition: 386,
  },
  {
    type: TokenTypes.OpenTagEnd,
    content: ">",
    startPosition: 387,
    endPosition: 387,
  },
  {
    type: TokenTypes.CloseTag,
    content: "</div>",
    startPosition: 388,
    endPosition: 393,
  },
  {
    type: TokenTypes.Text,
    content: "\n  \n  ",
    startPosition: 394,
    endPosition: 399,
  },
  {
    type: TokenTypes.OpenTagStart,
    content: "<div",
    startPosition: 400,
    endPosition: 403,
  },
  {
    type: TokenTypes.AttributeAssignment,
    content: "=",
    startPosition: 409,
    endPosition: 409,
  },
  {
    type: TokenTypes.AttributeValueWrapperStart,
    content: "'",
    startPosition: 410,
    endPosition: 410,
  },
  {
    type: TokenTypes.AttributeValue,
    content: "more spaces",
    startPosition: 411,
    endPosition: 421,
  },
  {
    type: TokenTypes.AttributeValueWrapperEnd,
    content: "'",
    startPosition: 422,
    endPosition: 422,
  },
  {
    type: TokenTypes.AttributeKey,
    content: "'key'",
    startPosition: 428,
    endPosition: 432,
  },
  {
    type: TokenTypes.AttributeKey,
    content: "spaced",
    startPosition: 434,
    endPosition: 439,
  },
  {
    type: TokenTypes.AttributeAssignment,
    content: "=",
    startPosition: 442,
    endPosition: 442,
  },
  {
    type: TokenTypes.AttributeValueWrapperStart,
    content: '"',
    startPosition: 448,
    endPosition: 448,
  },
  {
    type: TokenTypes.AttributeValue,
    content: "value",
    startPosition: 449,
    endPosition: 453,
  },
  {
    type: TokenTypes.AttributeValueWrapperEnd,
    content: '"',
    startPosition: 454,
    endPosition: 454,
  },
  {
    type: TokenTypes.AttributeKey,
    content: '"key-2"',
    startPosition: 461,
    endPosition: 467,
  },
  {
    type: TokenTypes.OpenTagEnd,
    content: ">",
    startPosition: 471,
    endPosition: 471,
  },
  {
    type: TokenTypes.CloseTag,
    content: "</div>",
    startPosition: 472,
    endPosition: 477,
  },
  {
    type: TokenTypes.Text,
    content: "\n",
    startPosition: 478,
    endPosition: 478,
  },
  {
    type: TokenTypes.CloseTag,
    content: "</div>",
    startPosition: 479,
    endPosition: 484,
  },
  {
    type: TokenTypes.Text,
    content: "\n\n",
    startPosition: 485,
    endPosition: 486,
  },
  {
    type: TokenTypes.OpenTagStart,
    content: "<span",
    startPosition: 487,
    endPosition: 491,
  },
  {
    type: TokenTypes.AttributeKey,
    content: "class",
    startPosition: 493,
    endPosition: 497,
  },
  {
    type: TokenTypes.AttributeAssignment,
    content: "=",
    startPosition: 498,
    endPosition: 498,
  },
  {
    type: TokenTypes.AttributeValueWrapperStart,
    content: '"',
    startPosition: 499,
    endPosition: 499,
  },
  {
    type: TokenTypes.AttributeValue,
    content: "another class",
    startPosition: 500,
    endPosition: 512,
  },
  {
    type: TokenTypes.AttributeValueWrapperEnd,
    content: '"',
    startPosition: 513,
    endPosition: 513,
  },
  {
    type: TokenTypes.AttributeKey,
    content: "custom-attr",
    startPosition: 515,
    endPosition: 525,
  },
  {
    type: TokenTypes.OpenTagEnd,
    content: ">",
    startPosition: 526,
    endPosition: 526,
  },
  {
    type: TokenTypes.CloseTag,
    content: "</span>",
    startPosition: 527,
    endPosition: 533,
  },
  {
    type: TokenTypes.Text,
    content: "\n",
    startPosition: 534,
    endPosition: 534,
  },
];
