import { TokenTypes } from "../../../constants";
import { Token } from "../../../types";

export default [
  { type: TokenTypes.Text, value: "\n", range: [0, 1] },
  { type: TokenTypes.OpenTagStart, value: "<div", range: [1, 5] },
  { type: TokenTypes.AttributeKey, value: "class", range: [6, 11] },
  { type: TokenTypes.AttributeAssignment, value: "=", range: [11, 12] },
  { type: TokenTypes.AttributeValueWrapperStart, value: '"', range: [12, 13] },
  { type: TokenTypes.AttributeValue, value: "test", range: [13, 17] },
  { type: TokenTypes.AttributeValueWrapperEnd, value: '"', range: [17, 18] },
  { type: TokenTypes.OpenTagEnd, value: ">", range: [18, 19] },
  { type: TokenTypes.Text, value: "\n  ", range: [19, 22] },
  { type: TokenTypes.OpenTagStart, value: "<custom-elem", range: [22, 34] },
  { type: TokenTypes.AttributeKey, value: "required", range: [35, 43] },
  { type: TokenTypes.AttributeAssignment, value: "=", range: [43, 44] },
  { type: TokenTypes.AttributeValueWrapperStart, value: '"', range: [44, 45] },
  { type: TokenTypes.AttributeValue, value: "requered", range: [45, 53] },
  { type: TokenTypes.AttributeValueWrapperEnd, value: '"', range: [53, 54] },
  { type: TokenTypes.AttributeKey, value: "data-some", range: [55, 64] },
  { type: TokenTypes.AttributeAssignment, value: "=", range: [64, 65] },
  { type: TokenTypes.AttributeValueWrapperStart, value: '"', range: [65, 66] },
  { type: TokenTypes.AttributeValue, value: "thing", range: [66, 71] },
  { type: TokenTypes.AttributeValueWrapperEnd, value: '"', range: [71, 72] },
  { type: TokenTypes.OpenTagEnd, value: ">", range: [72, 73] },
  { type: TokenTypes.CloseTag, value: "</custom-elem>", range: [73, 87] },
  { type: TokenTypes.Text, value: "\n  \n  ", range: [87, 93] },
  { type: TokenTypes.OpenTagStart, value: "<button", range: [93, 100] },
  { type: TokenTypes.AttributeKey, value: "disabled", range: [101, 109] },
  { type: TokenTypes.AttributeKey, value: "class", range: [110, 115] },
  { type: TokenTypes.AttributeAssignment, value: "=", range: [115, 116] },
  {
    type: TokenTypes.AttributeValueWrapperStart,
    value: '"',
    range: [116, 117],
  },
  { type: TokenTypes.AttributeValue, value: "button", range: [117, 123] },
  { type: TokenTypes.AttributeValueWrapperEnd, value: '"', range: [123, 124] },
  { type: TokenTypes.AttributeKey, value: "required", range: [125, 133] },
  { type: TokenTypes.OpenTagEnd, value: ">", range: [133, 134] },
  { type: TokenTypes.CloseTag, value: "</button>", range: [134, 143] },
  { type: TokenTypes.Text, value: "\n  ", range: [143, 146] },
  { type: TokenTypes.OpenTagStart, value: "<button", range: [146, 153] },
  { type: TokenTypes.AttributeKey, value: "disabled", range: [154, 162] },
  { type: TokenTypes.AttributeKey, value: "required", range: [163, 171] },
  { type: TokenTypes.OpenTagEnd, value: ">", range: [171, 172] },
  { type: TokenTypes.CloseTag, value: "</button>", range: [172, 181] },
  { type: TokenTypes.Text, value: "\n  ", range: [181, 184] },
  { type: TokenTypes.OpenTagStart, value: "<button", range: [184, 191] },
  { type: TokenTypes.AttributeKey, value: "disabled", range: [197, 205] },
  { type: TokenTypes.AttributeKey, value: "class", range: [211, 216] },
  { type: TokenTypes.AttributeAssignment, value: "=", range: [216, 217] },
  {
    type: TokenTypes.AttributeValueWrapperStart,
    value: '"',
    range: [217, 218],
  },
  {
    type: TokenTypes.AttributeValue,
    value: "button disabled",
    range: [218, 233],
  },
  { type: TokenTypes.AttributeValueWrapperEnd, value: '"', range: [233, 234] },
  { type: TokenTypes.AttributeKey, value: "test", range: [240, 244] },
  { type: TokenTypes.AttributeAssignment, value: "=", range: [244, 245] },
  {
    type: TokenTypes.AttributeValueWrapperStart,
    value: '"',
    range: [245, 246],
  },
  { type: TokenTypes.AttributeValue, value: "attribute", range: [246, 255] },
  { type: TokenTypes.AttributeValueWrapperEnd, value: '"', range: [255, 256] },
  { type: TokenTypes.AttributeKey, value: "another", range: [261, 268] },
  { type: TokenTypes.AttributeAssignment, value: "=", range: [268, 269] },
  {
    type: TokenTypes.AttributeValueWrapperStart,
    value: '"',
    range: [269, 270],
  },
  { type: TokenTypes.AttributeValue, value: "attribute", range: [270, 279] },
  { type: TokenTypes.AttributeValueWrapperEnd, value: '"', range: [279, 280] },
  { type: TokenTypes.AttributeKey, value: "custom-one", range: [285, 295] },
  { type: TokenTypes.OpenTagEnd, value: ">", range: [298, 299] },
  { type: TokenTypes.CloseTag, value: "</button>", range: [299, 308] },
  { type: TokenTypes.Text, value: "\n  \n  ", range: [308, 314] },
  { type: TokenTypes.OpenTagStart, value: "<div", range: [314, 318] },
  { type: TokenTypes.AttributeAssignment, value: "=", range: [319, 320] },
  {
    type: TokenTypes.AttributeValueWrapperStart,
    value: "'",
    range: [320, 321],
  },
  { type: TokenTypes.AttributeValue, value: "only value", range: [321, 331] },
  { type: TokenTypes.AttributeValueWrapperEnd, value: "'", range: [331, 332] },
  { type: TokenTypes.AttributeKey, value: "'only-key'", range: [333, 343] },
  { type: TokenTypes.AttributeKey, value: "another", range: [344, 351] },
  { type: TokenTypes.AttributeAssignment, value: "=", range: [351, 352] },
  {
    type: TokenTypes.AttributeValueWrapperStart,
    value: '"',
    range: [352, 353],
  },
  { type: TokenTypes.AttributeValue, value: "attr", range: [353, 357] },
  { type: TokenTypes.AttributeValueWrapperEnd, value: '"', range: [357, 358] },
  { type: TokenTypes.AttributeAssignment, value: "=", range: [359, 360] },
  {
    type: TokenTypes.AttributeValueWrapperStart,
    value: '"',
    range: [360, 361],
  },
  { type: TokenTypes.AttributeValue, value: "only-value-2", range: [361, 373] },
  { type: TokenTypes.AttributeValueWrapperEnd, value: '"', range: [373, 374] },
  { type: TokenTypes.AttributeKey, value: '"only-key-2"', range: [375, 387] },
  { type: TokenTypes.OpenTagEnd, value: ">", range: [387, 388] },
  { type: TokenTypes.CloseTag, value: "</div>", range: [388, 394] },
  { type: TokenTypes.Text, value: "\n  \n  ", range: [394, 400] },
  { type: TokenTypes.OpenTagStart, value: "<div", range: [400, 404] },
  { type: TokenTypes.AttributeAssignment, value: "=", range: [409, 410] },
  {
    type: TokenTypes.AttributeValueWrapperStart,
    value: "'",
    range: [410, 411],
  },
  { type: TokenTypes.AttributeValue, value: "more spaces", range: [411, 422] },
  { type: TokenTypes.AttributeValueWrapperEnd, value: "'", range: [422, 423] },
  { type: TokenTypes.AttributeKey, value: "'key'", range: [428, 433] },
  { type: TokenTypes.AttributeKey, value: "spaced", range: [434, 440] },
  { type: TokenTypes.AttributeAssignment, value: "=", range: [442, 443] },
  {
    type: TokenTypes.AttributeValueWrapperStart,
    value: '"',
    range: [448, 449],
  },
  { type: TokenTypes.AttributeValue, value: "value", range: [449, 454] },
  { type: TokenTypes.AttributeValueWrapperEnd, value: '"', range: [454, 455] },
  { type: TokenTypes.AttributeKey, value: '"key-2"', range: [461, 468] },
  { type: TokenTypes.OpenTagEnd, value: ">", range: [471, 472] },
  { type: TokenTypes.CloseTag, value: "</div>", range: [472, 478] },
  { type: TokenTypes.Text, value: "\n", range: [478, 479] },
  { type: TokenTypes.CloseTag, value: "</div>", range: [479, 485] },
  { type: TokenTypes.Text, value: "\n\n", range: [485, 487] },
  { type: TokenTypes.OpenTagStart, value: "<span", range: [487, 492] },
  { type: TokenTypes.AttributeKey, value: "class", range: [493, 498] },
  { type: TokenTypes.AttributeAssignment, value: "=", range: [498, 499] },
  {
    type: TokenTypes.AttributeValueWrapperStart,
    value: '"',
    range: [499, 500],
  },
  {
    type: TokenTypes.AttributeValue,
    value: "another class",
    range: [500, 513],
  },
  { type: TokenTypes.AttributeValueWrapperEnd, value: '"', range: [513, 514] },
  { type: TokenTypes.AttributeKey, value: "custom-attr", range: [515, 526] },
  { type: TokenTypes.OpenTagEnd, value: ">", range: [526, 527] },
  { type: TokenTypes.CloseTag, value: "</span>", range: [527, 534] },
  { type: TokenTypes.Text, value: "\n", range: [534, 535] },
];
