import { NodeTypes, TokenTypes } from "../../../constants";

export default [
  { type: TokenTypes.Text, value: "\n", range: [0, 1] },
  { type: TokenTypes.OpenTagStart, value: "<script", range: [1, 8] },
  { type: TokenTypes.AttributeKey, value: "src", range: [9, 12] },
  { type: TokenTypes.AttributeAssignment, value: "=", range: [12, 13] },
  { type: TokenTypes.AttributeValueWrapperStart, value: '"', range: [13, 14] },
  {
    type: TokenTypes.AttributeValue,
    value: "./some/script.js",
    range: [14, 30],
  },
  { type: TokenTypes.AttributeValueWrapperEnd, value: '"', range: [30, 31] },
  { type: TokenTypes.AttributeKey, value: "async", range: [32, 37] },
  { type: TokenTypes.OpenTagEnd, value: ">", range: [37, 38] },
  { type: TokenTypes.Text, value: "", range: [38, 38] },
  { type: TokenTypes.CloseTag, value: "</script>", range: [38, 47] },
  { type: TokenTypes.Text, value: "\n\n", range: [47, 49] },
  { type: TokenTypes.OpenTagStart, value: "<div", range: [49, 53] },
  { type: TokenTypes.OpenTagEnd, value: ">", range: [53, 54] },
  { type: TokenTypes.Text, value: "\n  test\n  \n  ", range: [54, 67] },
  { type: TokenTypes.OpenTagStart, value: "<script", range: [67, 74] },
  { type: TokenTypes.AttributeKey, value: "type", range: [75, 79] },
  { type: TokenTypes.AttributeAssignment, value: "=", range: [79, 80] },
  { type: TokenTypes.AttributeValueWrapperStart, value: '"', range: [80, 81] },
  {
    type: TokenTypes.AttributeValue,
    value: "text/javascript",
    range: [81, 96],
  },
  { type: TokenTypes.AttributeValueWrapperEnd, value: '"', range: [96, 97] },
  { type: TokenTypes.OpenTagEnd, value: ">", range: [97, 98] },
  {
    type: TokenTypes.Text,
    value: "\n    console.log('hello!') \n  ",
    range: [98, 128],
  },
  { type: TokenTypes.CloseTag, value: "</script>", range: [128, 137] },
  { type: TokenTypes.Text, value: "\n", range: [137, 138] },
  { type: TokenTypes.CloseTag, value: "</div>", range: [138, 144] },
  { type: TokenTypes.Text, value: "\n\n", range: [144, 146] },
  { type: TokenTypes.OpenTagStart, value: "<script", range: [146, 153] },
  { type: TokenTypes.AttributeKey, value: "type", range: [154, 158] },
  { type: TokenTypes.AttributeAssignment, value: "=", range: [158, 159] },
  {
    type: TokenTypes.AttributeValueWrapperStart,
    value: '"',
    range: [159, 160],
  },
  {
    type: TokenTypes.AttributeValue,
    value: "text/javascript",
    range: [160, 175],
  },
  { type: TokenTypes.AttributeValueWrapperEnd, value: '"', range: [175, 176] },
  { type: TokenTypes.OpenTagEnd, value: ">", range: [176, 177] },
  {
    type: TokenTypes.Text,
    value: "\n  console.log('another hello!') \n",
    range: [177, 211],
  },
  { type: TokenTypes.CloseTag, value: "</script>", range: [211, 220] },
  { type: TokenTypes.Text, value: "\n", range: [220, 221] },
];
