import { NodeTypes, TokenTypes } from "../../../constants";

export default [
  {
    type: TokenTypes.Text,
    content: "\n",
    startPosition: 0,
    endPosition: 0,
  },
  {
    type: TokenTypes.OpenTagStart,
    content: "<script",
    startPosition: 1,
    endPosition: 7,
  },
  {
    type: TokenTypes.AttributeKey,
    content: "src",
    startPosition: 9,
    endPosition: 11,
  },
  {
    type: TokenTypes.AttributeAssignment,
    content: "=",
    startPosition: 12,
    endPosition: 12,
  },
  {
    type: TokenTypes.AttributeValueWrapperStart,
    content: '"',
    startPosition: 13,
    endPosition: 13,
  },
  {
    type: TokenTypes.AttributeValue,
    content: "./some/script.js",
    startPosition: 14,
    endPosition: 29,
  },
  {
    type: TokenTypes.AttributeValueWrapperEnd,
    content: '"',
    startPosition: 30,
    endPosition: 30,
  },
  {
    type: TokenTypes.AttributeKey,
    content: "async",
    startPosition: 32,
    endPosition: 36,
  },
  {
    type: TokenTypes.OpenTagEnd,
    content: ">",
    startPosition: 37,
    endPosition: 37,
  },
  {
    type: TokenTypes.Text,
    content: "",
    startPosition: 38,
    endPosition: 37,
  },
  {
    type: TokenTypes.CloseTag,
    content: "</script>",
    startPosition: 38,
    endPosition: 46,
  },
  {
    type: TokenTypes.Text,
    content: "\n\n",
    startPosition: 47,
    endPosition: 48,
  },
  {
    type: TokenTypes.OpenTagStart,
    content: "<div",
    startPosition: 49,
    endPosition: 52,
  },
  {
    type: TokenTypes.OpenTagEnd,
    content: ">",
    startPosition: 53,
    endPosition: 53,
  },
  {
    type: TokenTypes.Text,
    content: "\n  test\n  \n  ",
    startPosition: 54,
    endPosition: 66,
  },
  {
    type: TokenTypes.OpenTagStart,
    content: "<script",
    startPosition: 67,
    endPosition: 73,
  },
  {
    type: TokenTypes.AttributeKey,
    content: "type",
    startPosition: 75,
    endPosition: 78,
  },
  {
    type: TokenTypes.AttributeAssignment,
    content: "=",
    startPosition: 79,
    endPosition: 79,
  },
  {
    type: TokenTypes.AttributeValueWrapperStart,
    content: '"',
    startPosition: 80,
    endPosition: 80,
  },
  {
    type: TokenTypes.AttributeValue,
    content: "text/javascript",
    startPosition: 81,
    endPosition: 95,
  },
  {
    type: TokenTypes.AttributeValueWrapperEnd,
    content: '"',
    startPosition: 96,
    endPosition: 96,
  },
  {
    type: TokenTypes.OpenTagEnd,
    content: ">",
    startPosition: 97,
    endPosition: 97,
  },
  {
    type: TokenTypes.Text,
    content: "\n    console.log('hello!') \n  ",
    startPosition: 98,
    endPosition: 127,
  },
  {
    type: TokenTypes.CloseTag,
    content: "</script>",
    startPosition: 128,
    endPosition: 136,
  },
  {
    type: TokenTypes.Text,
    content: "\n",
    startPosition: 137,
    endPosition: 137,
  },
  {
    type: TokenTypes.CloseTag,
    content: "</div>",
    startPosition: 138,
    endPosition: 143,
  },
  {
    type: TokenTypes.Text,
    content: "\n\n",
    startPosition: 144,
    endPosition: 145,
  },
  {
    type: TokenTypes.OpenTagStart,
    content: "<script",
    startPosition: 146,
    endPosition: 152,
  },
  {
    type: TokenTypes.AttributeKey,
    content: "type",
    startPosition: 154,
    endPosition: 157,
  },
  {
    type: TokenTypes.AttributeAssignment,
    content: "=",
    startPosition: 158,
    endPosition: 158,
  },
  {
    type: TokenTypes.AttributeValueWrapperStart,
    content: '"',
    startPosition: 159,
    endPosition: 159,
  },
  {
    type: TokenTypes.AttributeValue,
    content: "text/javascript",
    startPosition: 160,
    endPosition: 174,
  },
  {
    type: TokenTypes.AttributeValueWrapperEnd,
    content: '"',
    startPosition: 175,
    endPosition: 175,
  },
  {
    type: TokenTypes.OpenTagEnd,
    content: ">",
    startPosition: 176,
    endPosition: 176,
  },
  {
    type: TokenTypes.Text,
    content: "\n  console.log('another hello!') \n",
    startPosition: 177,
    endPosition: 210,
  },
  {
    type: TokenTypes.CloseTag,
    content: "</script>",
    startPosition: 211,
    endPosition: 219,
  },
  {
    type: TokenTypes.Text,
    content: "\n",
    startPosition: 220,
    endPosition: 220,
  },
];
