import { NodeTypes, TokenTypes } from "../../../constants";

export default [
  { type: TokenTypes.Text, value: "\n", range: [0, 1] },
  { type: TokenTypes.OpenTagStart, value: "<style", range: [1, 7] },
  { type: TokenTypes.OpenTagEnd, value: ">", range: [7, 8] },
  {
    type: TokenTypes.Text,
    value: "\n  body {\n    background-color: red;\n  }\n",
    range: [8, 49],
  },
  { type: TokenTypes.CloseTag, value: "</style>", range: [49, 57] },
  { type: TokenTypes.Text, value: "\n\n", range: [57, 59] },
  { type: TokenTypes.OpenTagStart, value: "<div", range: [59, 63] },
  { type: TokenTypes.OpenTagEnd, value: ">", range: [63, 64] },
  { type: TokenTypes.Text, value: "\n  test\n  \n  ", range: [64, 77] },
  { type: TokenTypes.OpenTagStart, value: "<style", range: [77, 83] },
  { type: TokenTypes.AttributeKey, value: "type", range: [84, 88] },
  { type: TokenTypes.AttributeAssignment, value: "=", range: [88, 89] },
  { type: TokenTypes.AttributeValueWrapperStart, value: '"', range: [89, 90] },
  { type: TokenTypes.AttributeValue, value: "text/css", range: [90, 98] },
  { type: TokenTypes.AttributeValueWrapperEnd, value: '"', range: [98, 99] },
  { type: TokenTypes.AttributeKey, value: "rel", range: [100, 103] },
  { type: TokenTypes.AttributeAssignment, value: "=", range: [103, 104] },
  {
    type: TokenTypes.AttributeValueWrapperStart,
    value: '"',
    range: [104, 105],
  },
  { type: TokenTypes.AttributeValue, value: "stylesheet", range: [105, 115] },
  { type: TokenTypes.AttributeValueWrapperEnd, value: '"', range: [115, 116] },
  { type: TokenTypes.OpenTagEnd, value: ">", range: [116, 117] },
  {
    type: TokenTypes.Text,
    value: "\n    body {\n      background-color: white;\n    }\n  ",
    range: [117, 168],
  },
  { type: TokenTypes.CloseTag, value: "</style>", range: [168, 176] },
  { type: TokenTypes.Text, value: "\n", range: [176, 177] },
  { type: TokenTypes.CloseTag, value: "</div>", range: [177, 183] },
  { type: TokenTypes.Text, value: "\n\n", range: [183, 185] },
  { type: TokenTypes.OpenTagStart, value: "<style", range: [185, 191] },
  { type: TokenTypes.AttributeKey, value: "type", range: [192, 196] },
  { type: TokenTypes.AttributeAssignment, value: "=", range: [196, 197] },
  {
    type: TokenTypes.AttributeValueWrapperStart,
    value: '"',
    range: [197, 198],
  },
  { type: TokenTypes.AttributeValue, value: "text/css", range: [198, 206] },
  { type: TokenTypes.AttributeValueWrapperEnd, value: '"', range: [206, 207] },
  { type: TokenTypes.AttributeKey, value: "rel", range: [208, 211] },
  { type: TokenTypes.AttributeAssignment, value: "=", range: [211, 212] },
  {
    type: TokenTypes.AttributeValueWrapperStart,
    value: '"',
    range: [212, 213],
  },
  { type: TokenTypes.AttributeValue, value: "stylesheet", range: [213, 223] },
  { type: TokenTypes.AttributeValueWrapperEnd, value: '"', range: [223, 224] },
  { type: TokenTypes.OpenTagEnd, value: ">", range: [224, 225] },
  {
    type: TokenTypes.Text,
    value: "\n  body {\n    background-color: black;\n  }\n",
    range: [225, 268],
  },
  { type: TokenTypes.CloseTag, value: "</style>", range: [268, 276] },
  { type: TokenTypes.Text, value: "\n", range: [276, 277] },
];
