import { NodeTypes, TokenTypes } from "../../../constants";

export default [
  {
    type: TokenTypes.Text,
    content: "\n",
    startPosition: 0,
    endPosition: 0,
  },
  {
    type: TokenTypes.OpenTagStart,
    content: "<style",
    startPosition: 1,
    endPosition: 6,
  },
  {
    type: TokenTypes.OpenTagEnd,
    content: ">",
    startPosition: 7,
    endPosition: 7,
  },
  {
    type: TokenTypes.Text,
    content: "\n  body {\n    background-color: red;\n  }\n",
    startPosition: 8,
    endPosition: 48,
  },
  {
    type: TokenTypes.CloseTag,
    content: "</style>",
    startPosition: 49,
    endPosition: 56,
  },
  {
    type: TokenTypes.Text,
    content: "\n\n",
    startPosition: 57,
    endPosition: 58,
  },
  {
    type: TokenTypes.OpenTagStart,
    content: "<div",
    startPosition: 59,
    endPosition: 62,
  },
  {
    type: TokenTypes.OpenTagEnd,
    content: ">",
    startPosition: 63,
    endPosition: 63,
  },
  {
    type: TokenTypes.Text,
    content: "\n  test\n  \n  ",
    startPosition: 64,
    endPosition: 76,
  },
  {
    type: TokenTypes.OpenTagStart,
    content: "<style",
    startPosition: 77,
    endPosition: 82,
  },
  {
    type: TokenTypes.AttributeKey,
    content: "type",
    startPosition: 84,
    endPosition: 87,
  },
  {
    type: TokenTypes.AttributeAssignment,
    content: "=",
    startPosition: 88,
    endPosition: 88,
  },
  {
    type: TokenTypes.AttributeValueWrapperStart,
    content: '"',
    startPosition: 89,
    endPosition: 89,
  },
  {
    type: TokenTypes.AttributeValue,
    content: "text/css",
    startPosition: 90,
    endPosition: 97,
  },
  {
    type: TokenTypes.AttributeValueWrapperEnd,
    content: '"',
    startPosition: 98,
    endPosition: 98,
  },
  {
    type: TokenTypes.AttributeKey,
    content: "rel",
    startPosition: 100,
    endPosition: 102,
  },
  {
    type: TokenTypes.AttributeAssignment,
    content: "=",
    startPosition: 103,
    endPosition: 103,
  },
  {
    type: TokenTypes.AttributeValueWrapperStart,
    content: '"',
    startPosition: 104,
    endPosition: 104,
  },
  {
    type: TokenTypes.AttributeValue,
    content: "stylesheet",
    startPosition: 105,
    endPosition: 114,
  },
  {
    type: TokenTypes.AttributeValueWrapperEnd,
    content: '"',
    startPosition: 115,
    endPosition: 115,
  },
  {
    type: TokenTypes.OpenTagEnd,
    content: ">",
    startPosition: 116,
    endPosition: 116,
  },
  {
    type: TokenTypes.Text,
    content: "\n    body {\n      background-color: white;\n    }\n  ",
    startPosition: 117,
    endPosition: 167,
  },
  {
    type: TokenTypes.CloseTag,
    content: "</style>",
    startPosition: 168,
    endPosition: 175,
  },
  {
    type: TokenTypes.Text,
    content: "\n",
    startPosition: 176,
    endPosition: 176,
  },
  {
    type: TokenTypes.CloseTag,
    content: "</div>",
    startPosition: 177,
    endPosition: 182,
  },
  {
    type: TokenTypes.Text,
    content: "\n\n",
    startPosition: 183,
    endPosition: 184,
  },
  {
    type: TokenTypes.OpenTagStart,
    content: "<style",
    startPosition: 185,
    endPosition: 190,
  },
  {
    type: TokenTypes.AttributeKey,
    content: "type",
    startPosition: 192,
    endPosition: 195,
  },
  {
    type: TokenTypes.AttributeAssignment,
    content: "=",
    startPosition: 196,
    endPosition: 196,
  },
  {
    type: TokenTypes.AttributeValueWrapperStart,
    content: '"',
    startPosition: 197,
    endPosition: 197,
  },
  {
    type: TokenTypes.AttributeValue,
    content: "text/css",
    startPosition: 198,
    endPosition: 205,
  },
  {
    type: TokenTypes.AttributeValueWrapperEnd,
    content: '"',
    startPosition: 206,
    endPosition: 206,
  },
  {
    type: TokenTypes.AttributeKey,
    content: "rel",
    startPosition: 208,
    endPosition: 210,
  },
  {
    type: TokenTypes.AttributeAssignment,
    content: "=",
    startPosition: 211,
    endPosition: 211,
  },
  {
    type: TokenTypes.AttributeValueWrapperStart,
    content: '"',
    startPosition: 212,
    endPosition: 212,
  },
  {
    type: TokenTypes.AttributeValue,
    content: "stylesheet",
    startPosition: 213,
    endPosition: 222,
  },
  {
    type: TokenTypes.AttributeValueWrapperEnd,
    content: '"',
    startPosition: 223,
    endPosition: 223,
  },
  {
    type: TokenTypes.OpenTagEnd,
    content: ">",
    startPosition: 224,
    endPosition: 224,
  },
  {
    type: TokenTypes.Text,
    content: "\n  body {\n    background-color: black;\n  }\n",
    startPosition: 225,
    endPosition: 267,
  },
  {
    type: TokenTypes.CloseTag,
    content: "</style>",
    startPosition: 268,
    endPosition: 275,
  },
  {
    type: TokenTypes.Text,
    content: "\n",
    startPosition: 276,
    endPosition: 276,
  },
];
